package Hibernate.POJO;
// Generated 20-may-2015 20:43:41 by Hibernate Tools 4.3.1



/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private String nombre;
     private String tipo;
     private String descripcion;

    public Materia() {
    }

    public Materia(String nombre, String tipo, String descripcion) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.descripcion = descripcion;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


