package Hibernate.POJO;
// Generated 20-may-2015 20:43:41 by Hibernate Tools 4.3.1



/**
 * Objetos generated by hbm2java
 */
public class Objetos  implements java.io.Serializable {


     private String nombre;
     private String descripcion;

    public Objetos() {
    }

    public Objetos(String nombre, String descripcion) {
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


