package Hibernate.POJO;
// Generated 20-may-2015 20:43:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Opiniones generated by hbm2java
 */
public class Opiniones  implements java.io.Serializable {


     private Date fecha;
     private String nombre;
     private String email;
     private String opinion;

    public Opiniones() {
    }

    public Opiniones(Date fecha, String nombre, String email, String opinion) {
       this.fecha = fecha;
       this.nombre = nombre;
       this.email = email;
       this.opinion = opinion;
    }
   
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }




}


