package Hibernate.POJO;
// Generated 20-may-2015 20:43:41 by Hibernate Tools 4.3.1



/**
 * Personajes generated by hbm2java
 */
public class Personajes  implements java.io.Serializable {


     private String nombre;
     private String imagen;
     private String edad;
     private String ocupacion;
     private String arma;
     private String fechana;
     private String lugarna;

    public Personajes() {
    }

    public Personajes(String nombre, String imagen, String edad, String ocupacion, String arma, String fechana, String lugarna) {
       this.nombre = nombre;
       this.imagen = imagen;
       this.edad = edad;
       this.ocupacion = ocupacion;
       this.arma = arma;
       this.fechana = fechana;
       this.lugarna = lugarna;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getArma() {
        return this.arma;
    }
    
    public void setArma(String arma) {
        this.arma = arma;
    }
    public String getFechana() {
        return this.fechana;
    }
    
    public void setFechana(String fechana) {
        this.fechana = fechana;
    }
    public String getLugarna() {
        return this.lugarna;
    }
    
    public void setLugarna(String lugarna) {
        this.lugarna = lugarna;
    }




}


