package Hibernate.POJO;
// Generated 20-may-2015 20:43:41 by Hibernate Tools 4.3.1



/**
 * Personajessecundarios generated by hbm2java
 */
public class Personajessecundarios  implements java.io.Serializable {


     private String nombre;
     private String ocupacion;
     private String fechana;
     private String lugarna;

    public Personajessecundarios() {
    }

    public Personajessecundarios(String nombre, String ocupacion, String fechana, String lugarna) {
       this.nombre = nombre;
       this.ocupacion = ocupacion;
       this.fechana = fechana;
       this.lugarna = lugarna;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getFechana() {
        return this.fechana;
    }
    
    public void setFechana(String fechana) {
        this.fechana = fechana;
    }
    public String getLugarna() {
        return this.lugarna;
    }
    
    public void setLugarna(String lugarna) {
        this.lugarna = lugarna;
    }




}


